-- Table for search index data
CREATE TABLE IF NOT EXISTS PREFIX_searchai_index (
    ID int(11) NOT NULL AUTO_INCREMENT,
    ELEMENT_ID int(11) NOT NULL,
    SITE_ID char(2) NOT NULL,
    CONTENT text NOT NULL,
    DATE_CREATE datetime NOT NULL,
    DATE_UPDATE datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY ELEMENT_ID (ELEMENT_ID),
    KEY SITE_ID (SITE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table for search suggestions cache
CREATE TABLE IF NOT EXISTS PREFIX_searchai_suggestions (
    ID int(11) NOT NULL AUTO_INCREMENT,
    QUERY varchar(255) NOT NULL,
    SUGGESTIONS text NOT NULL,
    HIT_COUNT int(11) DEFAULT 0,
    DATE_CREATE datetime NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY QUERY (QUERY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table for LLM request logs
CREATE TABLE IF NOT EXISTS PREFIX_searchai_llm_logs (
    ID int(11) NOT NULL AUTO_INCREMENT,
    REQUEST_ID varchar(64) NOT NULL,
    PROMPT text NOT NULL,
    RESPONSE text NOT NULL,
    TOKENS_USED int(11) DEFAULT 0,
    DATE_CREATE datetime NOT NULL,
    PRIMARY KEY (ID),
    KEY REQUEST_ID (REQUEST_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
